#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# https://wiki.archlinux.org/index.php/Fzf
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

eval "$(fasd --init auto)"

# Some functions to load into zsh
fpath=( $HOME/documents/zsh_functions $fpath )
autoload -Uz mkcd vimag vimfind vimgit mkcp backport

#
# Configure gpg and ssh agents: https://wiki.archlinux.org/index.php/GnuPG
#
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
  # Load identities.
  if ssh-add -l 2>&1 | grep -q 'The agent has no identities'; then
    if [[ -n "$DISPLAY" && -x "$SSH_ASKPASS" ]]; then
      ssh-add ~/.ssh/id_rsa < /dev/null 2> /dev/null
    else
      ssh-add ~/.ssh/id_rsa 2> /dev/null
    fi
  fi
fi
# Set GPG TTY
export GPG_TTY=$(tty)
# Refresh gpg-agent tty in case user switches into an X session
gpg-connect-agent updatestartuptty /bye >/dev/null

#
# Aliases
#

alias ls='exa -F --group-directories-first --color=auto'
alias vim=nvim
alias pacman="pacman --hookdir $HOME/.config/pacman/hooks"
alias pacmatic="pacmatic --hookdir $HOME/.config/pacman/hooks"
